
function [out1,out2] = fname (in1,in2)

function [out1] = fname (in1,in2)

function out1 = fname (in1,in2)

function fname (in1,in2)

%

function [out1,out2] = fname (in1,in2,...
                           in3)

function [out1] = fname (in1,in2,...
                           in3)

function out1 = fname (in1,in2,...
                     in3)

function fname (in1,in2,...
              in3)

%

function [out1,out2] = fname (in1,in2,...
                           in3,...
                           in4)

function [out1] = fname (in1,in2,...
                      in3,...
                      in4...
                      )

function out1 = fname (in1,in2,...
                     in3,...
                     in4...
                     )

function fname (in1,in2,...
              in3,...
              in4...
              )

%

function [out1,out2] = fname (in1,in2,...
                           in3,in4,...
                           in5,in6,in7...
                           )

%